name: Build APPX Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NuGet
        run: nuget restore Percentage.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Install Windows SDK
        run: choco install windows-sdk -y

      - name: Build solution
        run: msbuild.exe Percentage.sln /p:Configuration=Release /p:Platform="x86"

      - name: Create APPX package
        run: |
          mkdir Packaging\Output
          makeappx.exe pack /d Packaging /p Packaging\Output\BatteryPercentageIcon.appx

      - name: Sign APPX package
        env:
          CERTIFICATE_BASE64: ${{ secrets.CERTIFICATE_BASE64 }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
        run: |
          echo "$CERTIFICATE_BASE64" | base64 -d > cert.pfx
          signtool sign /fd SHA256 /a /f cert.pfx /p "$CERTIFICATE_PASSWORD" Packaging\Output\BatteryPercentageIcon.appx

      - name: Upload APPX
        uses: actions/upload-artifact@v3
        with:
          name: BatteryPercentageIcon
          path: Packaging\Output\BatteryPercentageIcon.appx
